In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/artempolyakov/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/artempolyakov/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/artempolyakov/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/artempolyakov/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/artempolyakov/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/artempolyakov/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/artempolyakov/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/artempolyakov/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/artempolyakov/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/artempolyakov/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
print(pd.__version__)

2.3.3

In [4]:
print(pd.__name__)

pandas

In [3]:
countries = pd.Series(
    data = ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ'],
    name = 'countries'
)
display(countries)

UK       Англия
CA       Канада
US          США
RU       Россия
UA      Украина
BY     Беларусь
KZ    Казахстан
Name: countries, dtype: object

In [ ]:
# names = ['chlorhexidine', 'cyntomycin', 'afobazol']
# counts = [15, 18, 7]

import pandas as pd

def create_medications(names, counts):
    medications = pd.Series(
        data = counts,
        index = names,
        name = 'medicati'
    )
    return medications

def get_percent(medications, name):
    return medications[name] / medications.sum() * 100

names=['chlorhexidine', 'cyntomycin', 'afobazol']
counts=[15, 18, 7]
medications = create_medications(names, counts)


print(medications)
print(get_percent(medications, 'chlorhexidine'))

chlorhexidine    15
cyntomycin       18
afobazol          7
Name: medicati, dtype: int64
37.5

In [13]:


import pandas as pd

income = [478, 512, 196]
expenses = [156, 130, 270]
years = [2018, 2019, 2020]


def create_companyDF(income, expenses, years):
    df = pd.DataFrame(
        {
        'Income': income,
        'Expenses': expenses
        },
        index = years
    )
    return df

def get_profit(df, year):
    if year not in df.index:
        return None

    return df.loc[year, 'Income'] - df.loc[year, 'Expenses']

In [14]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})

countries_df.to_csv('/Users/artempolyakov/Documents/Курсы/СкилФектори/IDE/Блок 1 (прочие файлы)/Pandas/Skillfactory/countries.csv', index=False, sep=';')

In [ ]:
countries_data = pd.read_csv('/Users/artempolyakov/Documents/Курсы/СкилФектори/IDE/Блок 1 (прочие файлы)/Pandas/Skillfactory/countries.csv', sep=';')
display(countries_data)

     country  population      area
0     Англия       56.29    133396
1     Канада       38.05   9984670
2        США      322.28   9826630
3     Россия      146.24  17125191
4    Украина       45.50    603628
5   Беларусь        9.50    207600
6  Казахстан       17.04   2724902

In [16]:
data = pd.read_csv('https://raw.githubusercontent.com/esabunor/MLWorkspace/master/melb_data.csv')
display(data)

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017,6.8,...,2.0,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [55]:
melb_data = pd.read_csv('/Users/artempolyakov/Documents/Курсы/СкилФектори/IDE/Блок 1 (прочие файлы)/Pandas/Skillfactory/melb_data.csv', sep=',')
# display(melb_data)


# # df.loc[year, 'Income']

# print(melb_data.loc[15, 'Price'])
# print(melb_data.loc[90, 'Date'])

# 3521 - Landsize
# 1690

# print(melb_data.loc[3521, 'Landsize']/melb_data.loc[1690, 'Landsize'])

display(melb_data.head(7))
# melb_data.info()

# melb_data['Car'] = melb_data['Car'].astype('int64')
# melb_data['Bedroom'] = melb_data['Bedroom'].astype('int64')
# melb_data['Bathroom'] = melb_data['Bathroom'].astype('int64')
# melb_data['Propertycount'] = melb_data['Propertycount'].astype('int64')
# melb_data['YearBuilt'] = melb_data['YearBuilt'].astype('int64')
# melb_data.info()


# melb_data.describe().loc[:, ['Distance', 'BuildingArea' , 'Price']]
melb_data['Type'].value_counts(normalize=True)

# melb_data.describe()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,126.0,1970.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,126.0,1970.0,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,"-37.8072, 144.9941"
5,5,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,7/05/2016,2.5,...,0.0,181.0,126.0,1970.0,Yarra,-37.8041,144.9953,Northern Metropolitan,4019.0,"-37.8041, 144.9953"
6,6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,...,0.0,245.0,210.0,1910.0,Yarra,-37.8024,144.9993,Northern Metropolitan,4019.0,"-37.8024, 144.9993"

Type
h    0.695803
u    0.222165
t    0.082032
Name: proportion, dtype: float64

In [48]:
print(melb_data['Price'].mean(axis=0))
# 1075684.079455081

1075684.079455081

In [54]:
print(round(melb_data['Distance'].std()))

6

In [58]:

BuildingArea_median = melb_data['BuildingArea'].median()
BuildingArea_mean = melb_data['BuildingArea'].mean()

print((BuildingArea_median - BuildingArea_mean)/BuildingArea_mean)

-0.09764079662364533

In [59]:
# Rooms

print(melb_data['Rooms'].mode())

0    3
Name: Rooms, dtype: int64

In [60]:
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  float64
 12  Bathroom       13580 non-null  float64
 13  Car            13580 non-null  float64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  float64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  float64
 22  Coordinates    13580 non-null  object
dtypes: float64(11), int64(3), object(9)
memory usage: 2.4+ MB

In [63]:
print(melb_data[melb_data['Bathroom'] == 0].count)

<bound method DataFrame.count of        index           Suburb            Address  Rooms Type      Price  \
139      139       Alphington        6 Naroon Rd      3    h  1485000.0
281      281         Armadale    3/50 Denbigh Rd      2    u   546000.0
505      505        Balaclava     5/11 Albion St      2    u   497500.0
584      584           Balwyn     5 Shrimpton Ct      2    h  1010000.0
913      913   Bentleigh East    579 Warrigal Rd      3    h   700000.0
1063    1063         Brighton          17 New St      3    h  1900000.0
1070    1070         Brighton        1/5 Webb St      3    t  1067000.0
1593    1593       Camberwell   5 Nicholsdale Rd      4    h  1400000.0
2253    2253      Elsternwick    5/29 Nepean Hwy      2    u   410000.0
2777    2777        Glen Iris         25 Hope St      2    h   845000.0
2797    2797        Glen Iris        130 High St      4    h  1550000.0
2808    2808        Glen Iris    1/64 Edgar St N      2    u   545000.0
3390    3390          Ivanhoe  5/125 Locksley Rd      2    u   460000.0
3556    3556       Kensington      7/51 Epsom Rd      2    u   526000.0
3787    3787          Malvern       42 Cressy St      2    h   780000.0
4880    4880          Preston       19 Malpas St      4    h  1004000.0
5535    5535  South Melbourne          3 Park Pl      1    u   760500.0
5642    5642      South Yarra   82/390 Toorak Rd      3    u  1072000.0
5711    5711      South Yarra     2/28 Tivoli Pl      2    u   910000.0
6392    6392           Toorak   1/183 Kooyong Rd      2    u   857000.0
6406    6406           Toorak   6/183 Kooyong Rd      2    u   866000.0
6651    6651       Yarraville    1/53 Stephen St      2    u   410000.0
6671    6671       Yarraville     1a Kingston St      2    h   610000.0
6856    6856   East Melbourne     37/22 Agnes St      2    u   740000.0
6866    6866   East Melbourne    9/35 Powlett St      2    u   872000.0
6938    6938          Fawkner      1/66 Lorne St      3    u   470000.0
7494    7494     Balwyn North   215 Doncaster Rd      3    h  1670000.0
8010    8010          Ivanhoe     1/53 Norman St      3    t  1060000.0
8271    8271          Preston       86 Malpas St      3    h  1010000.0
9090    9090   Caulfield East     5/33 Grange Rd      2    u   350000.0
9917    9917         Hawthorn     1/30 Lisson Gr      2    h  1480000.0
10795  10795          Preston     24 Mitchell St      3    h  1150000.0
10895  10895        Balaclava    9/36 The Avenue      2    u   700000.0
11204  11204        St Albans       148 Power St      3    h   702000.0

      Method        SellerG        Date  Distance  ...  Car  Landsize  \
139       SP        McGrath  28/08/2016       6.4  ...  0.0     597.0
281       SP  hockingstuart  30/07/2016       6.3  ...  0.0       0.0
505       PI  hockingstuart  28/08/2016       6.6  ...  0.0       0.0
584       PI       Marshall  30/07/2016       9.7  ...  0.0    1611.0
913        S        Thomson  22/05/2016      13.9  ...  0.0     456.0
1063       S       Marshall   6/08/2016      11.2  ...  0.0       0.0
1070       S            Kay   7/05/2016      11.2  ...  1.0       0.0
1593      PI         Jellis  16/04/2016       7.8  ...  0.0     693.0
2253      VB           Gary  28/05/2016       8.5  ...  0.0       0.0
2777       S           Noel  10/09/2016       9.2  ...  0.0     207.0
2797      PI         Jellis  14/05/2016       9.2  ...  0.0     769.0
2808       S      Fletchers  16/07/2016       9.2  ...  0.0       0.0
3390      VB      Fletchers  16/04/2016       7.9  ...  0.0       0.0
3556       S         Nelson  22/08/2016       4.2  ...  0.0       0.0
3787      VB         Jellis  14/05/2016       7.4  ...  0.0       0.0
4880       S         Nelson   3/09/2016       8.8  ...  0.0     650.0
5535       S       Marshall   4/06/2016       2.1  ...  0.0     438.0
5642       S            Kay  13/08/2016       3.3  ...  0.0       0.0
5711       S       Williams  28/08/2016       3.3  ...  0.0       0.0
6392       S          Walsh  22/08/2016       4.6  ...  0.0       0.0
6406       S       Marshall  30/07/2016       4.6  ...  0.0       0.0
6651      PI  hockingstuart   6/08/2016       7.0  ...  0.0       0.0
6671      SP            Jas  15/10/2016       7.0  ...  0.0      94.0
6856      SP       Woodards   8/10/2016       1.5  ...  0.0       0.0
6866       S         Dingle  28/05/2016       1.5  ...  0.0       0.0
6938      SP           Brad  26/07/2016      12.4  ...  0.0     261.0
7494       S  hockingstuart  29/04/2017       9.2  ...  0.0     818.0
8010       S   Purplebricks  29/04/2017       7.9  ...  0.0     219.0
8271      SP        McGrath  20/05/2017       8.8  ...  0.0     533.0
9090      SP           Gary   3/06/2017       8.4  ...  0.0       0.0
9917       S       Marshall  24/06/2017       5.3  ...  0.0     241.0
10795     SP        McGrath   8/07/2017       8.4  ...  0.0     502.0
10895     SP       Marshall  12/08/2017       6.4  ...  0.0       0.0
11204     SP        Sweeney  12/08/2017      14.0  ...  0.0     600.0

       BuildingArea  YearBuilt   CouncilArea  Lattitude  Longtitude  \
139           126.0     1970.0       Darebin  -37.77810   145.02840
281           126.0     1970.0   Stonnington  -37.85680   145.01610
505           126.0     1970.0  Port Phillip  -37.87390   144.99290
584           126.0     1970.0    Boroondara  -37.80920   145.10160
913           126.0     1970.0     Glen Eira  -37.93140   145.08080
1063          126.0     1970.0       Bayside  -37.93010   144.99350
1070          126.0     1970.0       Bayside  -37.91190   144.98710
1593          126.0     1935.0    Boroondara  -37.83600   145.09140
2253          126.0     1970.0     Glen Eira  -37.88630   144.99960
2777          126.0     1970.0   Stonnington  -37.86300   145.05010
2797          126.0     1970.0    Boroondara  -37.86280   145.07340
2808          126.0     1970.0   Stonnington  -37.85000   145.04650
3390          126.0     1970.0       Banyule  -37.76620   145.05160
3556          126.0     1970.0     Melbourne  -37.79190   144.92530
3787          126.0     1970.0   Stonnington  -37.85020   145.04180
4880          126.0     1970.0       Darebin  -37.73460   145.02260
5535          126.0     1970.0  Port Phillip  -37.83530   144.96000
5642          126.0     1970.0   Stonnington  -37.84070   145.00430
5711          126.0     1970.0     Melbourne  -37.83570   144.98590
6392          126.0     1970.0   Stonnington  -37.84580   145.02210
6406          126.0     1970.0   Stonnington  -37.84580   145.02210
6651          126.0     1970.0   Maribyrnong  -37.81290   144.89520
6671          126.0     1970.0   Maribyrnong  -37.81500   144.88270
6856          126.0     1970.0     Melbourne  -37.81770   144.98010
6866          126.0     1970.0     Melbourne  -37.81540   144.98510
6938          126.0     1970.0      Moreland  -37.71580   144.97220
7494          126.0     1970.0    Boroondara  -37.79390   145.08660
8010          126.0     1980.0       Banyule  -37.76790   145.04660
8271          126.0     1970.0       Darebin  -37.73360   145.01680
9090          126.0     1970.0     Glen Eira  -37.88385   145.04785
9917          126.0     1970.0    Boroondara  -37.82679   145.03021
10795         126.0     1970.0       Darebin  -37.74936   144.98949
10895         126.0     1970.0  Port Phillip  -37.87149   144.99746
11204         126.0     1970.0      Brimbank  -37.72945   144.79592

                  Regionname  Propertycount           Coordinates
139    Northern Metropolitan         2211.0    -37.7781, 145.0284
281    Southern Metropolitan         4836.0    -37.8568, 145.0161
505    Southern Metropolitan         2952.0    -37.8739, 144.9929
584    Southern Metropolitan         5682.0    -37.8092, 145.1016
913    Southern Metropolitan        10969.0    -37.9314, 145.0808
1063   Southern Metropolitan        10579.0    -37.9301, 144.9935
1070   Southern Metropolitan        10579.0    -37.9119, 144.9871
1593   Southern Metropolitan         8920.0     -37.836, 145.0914
2253   Southern Metropolitan         4898.0    -37.8863, 144.9996
2777   Southern Metropolitan        10412.0     -37.863, 145.0501
2797   Southern Metropolitan        10412.0    -37.8628, 145.0734
2808   Southern Metropolitan        10412.0      -37.85, 145.0465
3390    Eastern Metropolitan         5549.0    -37.7662, 145.0516
3556   Northern Metropolitan         5263.0    -37.7919, 144.9253
3787   Southern Metropolitan         4675.0    -37.8502, 145.0418
4880   Northern Metropolitan        14577.0    -37.7346, 145.0226
5535   Southern Metropolitan         5943.0      -37.8353, 144.96
5642   Southern Metropolitan        14887.0    -37.8407, 145.0043
5711   Southern Metropolitan        14887.0    -37.8357, 144.9859
6392   Southern Metropolitan         7217.0    -37.8458, 145.0221
6406   Southern Metropolitan         7217.0    -37.8458, 145.0221
6651    Western Metropolitan         6543.0    -37.8129, 144.8952
6671    Western Metropolitan         6543.0     -37.815, 144.8827
6856   Northern Metropolitan         3040.0    -37.8177, 144.9801
6866   Northern Metropolitan         3040.0    -37.8154, 144.9851
6938   Northern Metropolitan         5070.0    -37.7158, 144.9722
7494   Southern Metropolitan         7809.0    -37.7939, 145.0866
8010    Eastern Metropolitan         5549.0    -37.7679, 145.0466
8271   Northern Metropolitan        14577.0    -37.7336, 145.0168
9090   Southern Metropolitan          608.0  -37.88385, 145.04785
9917   Southern Metropolitan        11308.0  -37.82679, 145.03021
10795  Northern Metropolitan        14577.0  -37.74936, 144.98949
10895  Southern Metropolitan         2952.0  -37.87149, 144.99746
11204   Western Metropolitan        14042.0  -37.72945, 144.79592

[34 rows x 23 columns]>

In [73]:
# print(melb_data[(melb_data['SellerG'] == 'Nelson') & (melb_data['Price'] >= 3000000)].shape[0])

f_price = melb_data[melb_data['BuildingArea'] == 0]

print(f_price['Price'].min())

412500.0

In [77]:
filt = melb_data[(melb_data['Price'] < 1000000) & ((melb_data['Rooms'] > 5) | (melb_data['YearBuilt'] > 2015))]

print(round(filt['Price'].mean()))

769239

In [87]:
import pandas as pd

# 1. Загружаем данные в переменную (укажите корректный путь к исходному файлу)
students_performance = pd.read_csv(
    '/Users/artempolyakov/Documents/Курсы/СкилФектори/IDE/Блок 1 (прочие файлы)/Pandas/Skillfactory/students_performance.csv'
)

# 2. Проверяем, что данные загрузились
display(students_performance.head(10))

students_performance.info()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [97]:
# test preparation course
fltr = students_performance['math score'] == 0
mean_score = students_performance.loc[fltr, 'gender'].count()
print(mean_score)

1

In [99]:
# Группируем по lunch, выбираем все скоры и применяем describe()
table_1 = (
    students_performance
    .groupby('lunch')[['math score', 'reading score', 'writing score']]
    .describe()
    .round(2) # Округляем все числа до 2 знаков для удобства чтения
)
display(table_1)

             math score                                               \
                  count   mean    std   min   25%   50%   75%    max
lunch
free/reduced      355.0  58.92  15.16   0.0  49.0  60.0  69.0  100.0
standard          645.0  70.03  13.65  19.0  61.0  69.0  80.0  100.0

             reading score         ...              writing score         \
                     count   mean  ...   75%    max         count   mean
lunch                              ...
free/reduced         355.0  64.65  ...  75.0  100.0         355.0  63.02
standard             645.0  71.65  ...  82.0  100.0         645.0  70.82


                std   min   25%   50%   75%    max
lunch
free/reduced  15.43  10.0  53.0  64.0  74.0  100.0
standard      14.34  22.0  62.0  72.0  81.0  100.0

[2 rows x 24 columns]

In [100]:
students_performance['parental level of education'].value_counts(normalize=True)

parental level of education
some college          0.226
associate's degree    0.222
high school           0.196
some high school      0.179
bachelor's degree     0.118
master's degree       0.059
Name: proportion, dtype: float64